# Generated by Django 4.2.7 on 2024-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_name', models.CharField(max_length=255)),
                ('Visitor_address', models.TextField()),
                ('Visitor_mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
