# Generated by Django 4.2.7 on 2024-02-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='Visitor_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Visitor_mobile_number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Visitor_name',
            new_name='name',
        ),
    ]
